### ISSUE TITLE
Add `environment` field to code function handler

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool-json-schema#2]
The `code` function handler should accept a `environment` string:string-map like in the following example:

```yml
functions:

  auth:
    type: schemaExtension
    schema: my-schema.graphql
    handler:
      code:
        src: "my-script.js"
        environment:
          AUTH0_MASTER_TOKEN: prefix-${env:MY_AUTH0_TOKEN}
```
